name: 'GitHub Pages Deployment'

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site
        
    steps:
      - name: git / checkout
        uses: actions/checkout@v4

      - name: Node / install
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: npm / install
        run: npm install

      - name: npm / build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          npm run build

      - name: GitHub / upload artefacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub / deploy
        id: deployment
        uses: actions/deploy-pages@v4
