name: 'GitHub Pages Deployment'

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './site'
        
    steps:
      - name: 'git / checkout'
        uses: actions/checkout@v4

      - name: 'python / setup'
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: 'node / setup'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './site/package-lock.json'

      - name: 'svelte / install'
        run: npm install

      - name: 'svelte / build'
        env:
          BASE_PATH: '/${{ github.event.repository.name }}/site'
        run: |
          npm run buildx

      - name: 'github / upload artifacts'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site/build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 'github / deploy'
        id: deployment
        uses: actions/deploy-pages@v4
